name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main", "develop"]

jobs:
    style:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.14"

            - name: Install dependencies
              run: |
                  make req
                  make style-req
                  make tests-req

            - name: Run linters
              run: make lint

    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.14"

            - name: Install dependencies
              run: |
                  make req
                  make tests-req

            - name: Run tests
              run: make test-full
